# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_inst_mem_0_0/design_1_inst_mem_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_inst_mem_0_0 || ORIG_REF_NAME==design_1_inst_mem_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_0/design_1_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_0 || ORIG_REF_NAME==design_1_xlslice_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reg_file_0_0/design_1_reg_file_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_reg_file_0_0 || ORIG_REF_NAME==design_1_reg_file_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_2_0/design_1_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_2_0 || ORIG_REF_NAME==design_1_xlslice_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_3_0/design_1_xlslice_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_3_0 || ORIG_REF_NAME==design_1_xlslice_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sign_extend_0_0/design_1_sign_extend_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_sign_extend_0_0 || ORIG_REF_NAME==design_1_sign_extend_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_4_0/design_1_xlslice_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_4_0 || ORIG_REF_NAME==design_1_xlslice_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tags_and_ready_0_0/design_1_tags_and_ready_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_tags_and_ready_0_0 || ORIG_REF_NAME==design_1_tags_and_ready_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reorder_buffer_0_0/design_1_reorder_buffer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_reorder_buffer_0_0 || ORIG_REF_NAME==design_1_reorder_buffer_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rs_table_0_0/design_1_rs_table_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rs_table_0_0 || ORIG_REF_NAME==design_1_rs_table_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_5_0/design_1_xlslice_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_5_0 || ORIG_REF_NAME==design_1_xlslice_5_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_inputA_0/design_1_inputA_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_inputA_0 || ORIG_REF_NAME==design_1_inputA_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_inputA_0_0/design_1_inputA_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_inputA_0_0 || ORIG_REF_NAME==design_1_inputA_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_inputA_0_1/design_1_inputA_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_inputA_0_1 || ORIG_REF_NAME==design_1_inputA_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_inputA_0_2/design_1_inputA_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_inputA_0_2 || ORIG_REF_NAME==design_1_inputA_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_inputB_0_0/design_1_inputB_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_inputB_0_0 || ORIG_REF_NAME==design_1_inputB_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_inputB_0_1/design_1_inputB_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_inputB_0_1 || ORIG_REF_NAME==design_1_inputB_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_inputB_0_2/design_1_inputB_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_inputB_0_2 || ORIG_REF_NAME==design_1_inputB_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mux4_0_0/design_1_mux4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mux4_0_0 || ORIG_REF_NAME==design_1_mux4_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mux4_0_1/design_1_mux4_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mux4_0_1 || ORIG_REF_NAME==design_1_mux4_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_data_mem_0_0/design_1_data_mem_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_data_mem_0_0 || ORIG_REF_NAME==design_1_data_mem_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adder_0_0/design_1_adder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_adder_0_0 || ORIG_REF_NAME==design_1_adder_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adder_1_0/design_1_adder_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_adder_1_0 || ORIG_REF_NAME==design_1_adder_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_5_1/design_1_xlslice_5_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_5_1 || ORIG_REF_NAME==design_1_xlslice_5_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sign_extend_1_0/design_1_sign_extend_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_sign_extend_1_0 || ORIG_REF_NAME==design_1_sign_extend_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_alu0_0_0/design_1_alu0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_alu0_0_0 || ORIG_REF_NAME==design_1_alu0_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_6_0/design_1_xlslice_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_6_0 || ORIG_REF_NAME==design_1_xlslice_6_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_7_0/design_1_xlslice_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_7_0 || ORIG_REF_NAME==design_1_xlslice_7_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_instr_translator_0_0/design_1_instr_translator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_instr_translator_0_0 || ORIG_REF_NAME==design_1_instr_translator_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mult_div_0_0/design_1_mult_div_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mult_div_0_0 || ORIG_REF_NAME==design_1_mult_div_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cdb_0_0/design_1_cdb_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cdb_0_0 || ORIG_REF_NAME==design_1_cdb_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mux_0_0/design_1_mux_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mux_0_0 || ORIG_REF_NAME==design_1_mux_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mux_1_0/design_1_mux_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mux_1_0 || ORIG_REF_NAME==design_1_mux_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mux_2_0/design_1_mux_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mux_2_0 || ORIG_REF_NAME==design_1_mux_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_8_0/design_1_xlslice_8_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_8_0 || ORIG_REF_NAME==design_1_xlslice_8_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cm_sel_1_0/design_1_cm_sel_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cm_sel_1_0 || ORIG_REF_NAME==design_1_cm_sel_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_add4_0_0/design_1_add4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_add4_0_0 || ORIG_REF_NAME==design_1_add4_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reg0_0_0/design_1_reg0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_reg0_0_0 || ORIG_REF_NAME==design_1_reg0_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reg0_0_1/design_1_reg0_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_reg0_0_1 || ORIG_REF_NAME==design_1_reg0_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reg0_0_2/design_1_reg0_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_reg0_0_2 || ORIG_REF_NAME==design_1_reg0_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reg0_0_3/design_1_reg0_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_reg0_0_3 || ORIG_REF_NAME==design_1_reg0_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reg0_0_4/design_1_reg0_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_reg0_0_4 || ORIG_REF_NAME==design_1_reg0_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reg0_0_5/design_1_reg0_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_reg0_0_5 || ORIG_REF_NAME==design_1_reg0_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reg0_0_6/design_1_reg0_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_reg0_0_6 || ORIG_REF_NAME==design_1_reg0_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reg0_0_7/design_1_reg0_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_reg0_0_7 || ORIG_REF_NAME==design_1_reg0_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reg0_0_8/design_1_reg0_0_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_reg0_0_8 || ORIG_REF_NAME==design_1_reg0_0_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reg0_0_9/design_1_reg0_0_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_reg0_0_9 || ORIG_REF_NAME==design_1_reg0_0_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reg0_0_10/design_1_reg0_0_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_reg0_0_10 || ORIG_REF_NAME==design_1_reg0_0_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reg0_0_11/design_1_reg0_0_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_reg0_0_11 || ORIG_REF_NAME==design_1_reg0_0_11} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reg0_0_12/design_1_reg0_0_12.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_reg0_0_12 || ORIG_REF_NAME==design_1_reg0_0_12} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reg0_0_13/design_1_reg0_0_13.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_reg0_0_13 || ORIG_REF_NAME==design_1_reg0_0_13} -quiet] -quiet

# IP: bd/design_1/ip/design_1_stage_controller_0_0/design_1_stage_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_stage_controller_0_0 || ORIG_REF_NAME==design_1_stage_controller_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_stage_controller_1_0/design_1_stage_controller_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_stage_controller_1_0 || ORIG_REF_NAME==design_1_stage_controller_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_stage_controller_2_0/design_1_stage_controller_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_stage_controller_2_0 || ORIG_REF_NAME==design_1_stage_controller_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_stage_controller_3_0/design_1_stage_controller_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_stage_controller_3_0 || ORIG_REF_NAME==design_1_stage_controller_3_0} -quiet] -quiet

# XDC: /home/connor/Documents/mips/mips-core/mips-core.gen/sources_1/bd/design_1/design_1_ooc.xdc
